#DEPLOYMENT
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kubernetes.io/change-cause: "Actualización de inspeccion v0.2.2 y patronos v0.1.27"
  name: setrass-ecms-web-ui
  labels:
    app: web-ui

#REPLICASET
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web-ui
#POD
  template:
    metadata:
      labels:
        app: web-ui
    spec:
      containers:
      - name: web-ui
        image: 648505502080.dkr.ecr.us-east-1.amazonaws.com/setrass-ecms-web-ui:2.0.23

---
#SERVICE
apiVersion: v1
kind: Service
metadata:
  name: setrass-ecms-web-ui-svc
  labels:
    app: web-ui
spec:
  type: ClusterIP
  selector:
    app: web-ui
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

